language: emacs
sudo: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
  - cask emacs --version

env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.3-travis

matrix:
  fast_finish: true

script:
  - make check
